# Goal
bool start_tracking
---
# Result
bool success
---
# Feedback
int32 detected_poles_count  # Number of poles detected (0-4)
geometry_msgs/Point[] pole_positions  # Array of pole positions relative to LiDAR
float32[] pole_distances_x  # X distances from LiDAR for each pole
float32[] pole_distances_y  # Y distances from LiDAR for each pole
float32[] pole_confidences  # Confidence scores for each pole detection (0.0-1.0)